# here we need statements to insert supported stocks in this table

# CREATE TABLE Stock (
#     ticker_symbol VARCHAR(10) PRIMARY KEY,
#     sector ENUM(
#         'Aerospace & Defense',
#         'Automobiles',
#         'Banks',
#         'Biotechnology',
#         'Chemicals',
#         'Communication Services',
#         'Construction & Engineering',
#         'Construction Materials',
#         'Consumer Discretionary',
#         'Consumer Services',
#         'Consumer Staples',
#         'Electric Utilities',
#         'Energy',
#         'Entertainment',
#         'Financials',
#         'Food & Beverage',
#         'Gas Utilities',
#         'Hardware',
#         'Healthcare',
#         'Healthcare Equipment & Services',
#         'Household Products',
#         'Industrials',
#         'Information Technology',
#         'Insurance',
#         'Machinery',
#         'Materials',
#         'Media',
#         'Metals & Mining',
#         'Oil & Gas',
#         'Pharmaceuticals',
#         'Real Estate',
#         'Real Estate Investment Trusts (REITs)',
#         'Renewable Energy',
#         'Retail',
#         'Semiconductors',
#         'Software',
#         'Telecommunication Services',
#         'Utilities',
#         'Water Utilities'
#     )
# );
